name: engbase

channels:
  - default
  - conda-forge

dependencies:
  - python=3.8
  - numpy 
  - pandas
  - matplotlib
  - wntr
  - conda
  - networkx
  - pytest
  - fluids
  - thermo
  - pint
  - scipy
  - seaborn
  - coolprop
  - sphinx
  - pandoc
  - autopep8
  - notebook
  - jupyter_core
  - jupyter_client
  - jupyter_console
  - ipykernel
  - python
  - pip
  - requests
  - pytest
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - jupyter_core
  - jupyter_client
  - ipykernel
  - notebook
  - qtconsole
  - jupyter_console
  - ipywidgets
  - nbclient
  - nbformat
  - nbconvert
  - scipy
  - sympy
  - scikit-learn
  - coolprop
  - wntr
  - pandoc
  - cairo
  - pycairo
  - cairosvg
  - fire
  - pint
  - networkx
  - uncertainties
  - xlsxwriter
  - ipycanvas
  - watchdog
  - asttokens
  - toposort
  - fluids
  - thermo
  - bokeh
  - selenium